development:
  adapter: postgresql
  encoding: unicode
  database: periodic_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: periodic_test
  pool: 5
  host: localhost
  min_messages: fatal

production:
  adapter: postgresql
  encoding: unicode
  database: periodic_production
  pool: 5
  password:

cucumber:
  <<: *test